apiVersion: batch/v1
kind: Job
metadata:
  labels:
    app: test-job
    run: test-spark-label
  name: test-spark-job
  namespace: test-data-product
spec:
  ttlSecondsAfterFinished: 100
  template:
    metadata:
      labels:
        app: test-job
    spec:
      containers:
        - image: test-python:latest
          name: test-spark-image
          resources: {}
          imagePullPolicy: Never
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
      restartPolicy: Never
  podFailurePolicy:
    rules:
      - action: FailJob
        onExitCodes:
          containerName: test-spark-image      # optional
          operator: NotIn             # one of: In, NotIn
          values: [ 0 ]
